stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/make_data.py
    - src/get_data.py
    - src/load_data.py
    - data_given/data.csv
    outs:
    - data/raw/data_raw.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/data_raw.csv
    outs:
    - data/processed/train_data.csv
    - data/processed/test_data.csv 

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_data.csv
    - data/processed/test_data.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.LogisticRegression.params.C
    - estimators.LogisticRegression.params.penalty
    - estimators.LogisticRegression.params.solver
    metrics:
    - srcreport/scores.json:
        cache: false
    - srcreport/params.json:
        cache: false
    outs:
    - saved_models/model.joblib